from enum import StrEnum


class PermissionCode(StrEnum):
    DOCUMENT_VIEW = "DOCUMENT_VIEW"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"
    DOCUMENT_DOWNLOAD = "DOCUMENT_DOWNLOAD"
    RAG_QUERY = "RAG_QUERY"
    RAG_SENSITIVE_QUERY = "RAG_SENSITIVE_QUERY"
    REPORT_VIEW = "REPORT_VIEW"
    REPORT_CREATE = "REPORT_CREATE"
    REPORT_EXPORT = "REPORT_EXPORT"
    VISION_ANALYSIS = "VISION_ANALYSIS"
    CODE_GENERATE = "CODE_GENERATE"
    CODE_EXECUTE = "CODE_EXECUTE"
    SANDBOX_EXECUTE = "SANDBOX_EXECUTE"
    AUDIT_VIEW = "AUDIT_VIEW"
    USER_VIEW = "USER_VIEW"
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_DISABLE = "USER_DISABLE"
    DEPARTMENT_MANAGE = "DEPARTMENT_MANAGE"
    POSITION_MANAGE = "POSITION_MANAGE"
    PERMISSION_MANAGE = "PERMISSION_MANAGE"
    SECURITY_VIEW = "SECURITY_VIEW"
    SECURITY_MANAGE = "SECURITY_MANAGE"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"


PERMISSION_CODES = frozenset(code.value for code in PermissionCode)
